branches:
  only:
    - master
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  # 3.7 added manually to test matrix,
  # awaiting travis fix
  # see https://github.com/travis-ci/travis-ci/issues/9815
  # - "3.7"
  # - "3.8-dev"
install: 
  - pip install tox-travis
  - pip install codecov
matrix:
  include:
    - python: 3.6
      env: TOXENV=lint
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=isort
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
script: tox
after_success:
  - codecov
