[tool.poetry]
name = "quiz"
version = "0.2.3"
description = "Capable GraphQL client"
authors = ["Arie Bovenberg <a.c.bovenberg@gmail.com>"]
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
packages = [
    { include = "quiz", from = "src" },
]
readme = "README.rst"
include = ["HISTORY.rst", "README.rst"]
repository = "https://github.com/ariebovenberg/quiz"
keywords = [
    "http",
    "async",
    "graphql",
]

[tool.poetry.dependencies]
python = "^3.6"
importlib-metadata = {version = "^1.0", python = "<3.8"}
gentools = "^1.1.0"
snug = "^2.2.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.0"
isort = "^5.7.0"
mypy = "^0.812"
pytest = "^6.2.1"
tox = "^3.20.1"
black = "^20.8b1"
pytest-cov = "^2.11.1"
pytest-mock = "^3.6.1"
hypothesis = "^6.13.4"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
  \.eggs
| \.git
| \.mypy_cache
| \.tox
| \.venv
| _build
| build
| dist
)/
'''

[tool.isort]
line_length = 79
profile = 'black'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
